# Introduction: Let us now link the pods to the Deployment by updating selectors.
# Instruction: Add a property "matchLabels" under selector and copy the labels defined in the pod-definition under it.
# Note: this may not work in play-with-k8s as it runs on 1.8 version of kubernetes
# ------------------------------
#           BEFORE
# ------------------------------
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: frontend
#  labels:
#    app: mywebsite
#    tier: frontend
#spec:
#  replicas: 4
#  template:
#  selector:

# ------------------------------
#           AFTER
# ------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 4
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp